### ISSUE TITLE
Shell script to run wp-cli on all stacked sites

### ISSUE THREAD

**Issue by mircobabini** [WPFreighter/wp-freighter#15]
Following the instructions into the official docs but having issues on Siteground.

This is the script. Weird that it always shows the main site url, never looping on the stacked sites.
Also tried to echoing the $stacked_id var. That's correctly fetched 1, 2, 3... weird.

```sh
#!/bin/bash
stacked_ids=$( grep "\$stacked_mappings\[.\]" wp-config.php | awk -F '[' '{print $2}' | awk -F ']' '{print $1}' )

for stacked_id in ${stacked_ids}; do
    export STACKED_ID=$stacked_id
    echo "Cleanup cache for $( wp option get home )"
    wp cache flush; wp sg purge
    #wp theme update --all
    #wp plugin update --all
done
```

Maybe Siteground-only issue?

**Comment by austinginder** [comment]
Ah good catch. That was the original naming scheme. Docs have been corrected: https://wpfreighter.com/docs/.
